### ISSUE TITLE
what should I put in set engine path

### ISSUE THREAD

**Issue by researchase** [DanielBoxer/UVgami#2]
when I try the addon I get error that engine path is not set, I am not sure what should I enter here? please can you help
![image](https://github.com/DanielBoxer/UVgami/assets/5505550/8e80e48e-aa6f-4f30-b576-afa1eba8cfa1)

**Comment by danielboxer** [comment]
Download the engine from [here](https://github.com/DanielBoxer/UVgami/releases/latest) and then use the button on the right of the engine path field to locate it on your filesystem.

There's also some documentation in the Engine.zip folder that might be helpful.

**Comment by researchase** [comment]
Thank you so much for the help! its working now! awesome plugin.

**Comment by danielboxer** [comment]
Great! I'm glad you like it!
