### ISSUE TITLE
Engine path..?

### ISSUE THREAD

**Issue by apinanaivot** [DanielBoxer/UVgami#7]
"Engine path is incorrect." What engine path?

I can see an option to set it in the addon preferences "path to the unwrapping application stored on your computer", what unwrapping application? Why is there no explanation as to what it is anywhere?

If the installation requires something other than just installing the addon, perhaps it would make sense to explain the process instead of assuming that it's understood telepathically.

**Comment by danielboxer** [comment]
There's an `Engine.zip` file above `UVgami.zip` in the latest release. You need to download that as well as the add-on. The unwrapping application you need is Inside the engine folder along with a documentation pdf with install instructions.

I just added the docs to the repo so it's easier to find.

See also https://github.com/DanielBoxer/UVgami/issues/2

**Comment by apinanaivot** [comment]
Thank you!
